version: "2"
linters:
  enable:
    - dupl
  exclusions:
    generated: lax
    rules:
      - linters:
          - dupl
        path: internal/i18n/.*\.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
